# Generated by Django 4.2.29 on 2026-04-22 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTag',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('life_support', 'Life Support'), ('monitoring', 'Monitoring'), ('mobility', 'Mobility'), ('respiratory', 'Respiratory'), ('infection_control', 'Infection Control'), ('furniture', 'Furniture')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='beds_equipm_categor_58b0f7_idx'), models.Index(fields=['is_active'], name='beds_equipm_is_acti_8c0b5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=20)),
                ('bed_code', models.CharField(max_length=100, unique=True)),
                ('bed_type', models.CharField(choices=[('icu', 'ICU'), ('general', 'General'), ('isolation', 'Isolation'), ('nicu', 'NICU'), ('emergency', 'Emergency'), ('maternity', 'Maternity'), ('pediatric', 'Pediatric'), ('bariatric', 'Bariatric'), ('burn', 'Burn Unit'), ('psychiatric', 'Psychiatric'), ('recovery', 'Recovery'), ('observation', 'Observation')], default='general', max_length=20)),
                ('is_isolation', models.BooleanField(default=False)),
                ('gender_restriction', models.CharField(choices=[('none', 'None'), ('male_only', 'Male Only'), ('female_only', 'Female Only')], default='none', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('cleaning_required', 'Cleaning Required'), ('cleaning_in_progress', 'Cleaning In Progress'), ('under_maintenance', 'Under Maintenance'), ('blocked', 'Blocked'), ('isolation', 'Isolation')], default='available', max_length=30)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_reason', models.TextField(blank=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.TextField(blank=True)),
                ('under_maintenance_since', models.DateTimeField(blank=True, null=True)),
                ('maintenance_reason', models.TextField(blank=True)),
                ('occupied_since', models.DateTimeField(blank=True, null=True)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('bed_size', models.CharField(choices=[('standard', 'Standard'), ('large', 'Large'), ('bariatric', 'Bariatric'), ('pediatric', 'Pediatric')], default='standard', max_length=20)),
                ('max_patient_weight_kg', models.DecimalField(decimal_places=2, default=150.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_beds', to=settings.AUTH_USER_MODEL)),
                ('current_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_bed', to='admissions.admission')),
                ('equipment_tags', models.ManyToManyField(blank=True, related_name='beds', to='beds.equipmenttag')),
                ('reserved_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_reserved_bed', to='admissions.admissionrequest')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_status_changes', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='organizations.ward')),
            ],
            options={
                'ordering': ['ward__department__hospital', 'ward__name', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='BedStatusHistory',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('cleaning_required', 'Cleaning Required'), ('cleaning_in_progress', 'Cleaning In Progress'), ('under_maintenance', 'Under Maintenance'), ('blocked', 'Blocked'), ('isolation', 'Isolation')], max_length=30)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.admission')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='beds.bed')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['bed', '-changed_at'], name='beds_bedsta_bed_id_505ec5_idx'), models.Index(fields=['status', 'changed_at'], name='beds_bedsta_status_adb57c_idx')],
            },
        ),
        migrations.CreateModel(
            name='BedMaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('issue_description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_type', models.CharField(choices=[('repair', 'Repair'), ('preventive', 'Preventive Maintenance'), ('inspection', 'Inspection'), ('replacement', 'Part Replacement')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='beds.bed')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['bed', 'status'], name='beds_bedmai_bed_id_5b8e42_idx'), models.Index(fields=['severity', 'status'], name='beds_bedmai_severit_70fbb1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['ward', 'status'], name='beds_bed_ward_id_3352a5_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['ward', 'is_active'], name='beds_bed_ward_id_3444a7_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['status', 'bed_type'], name='beds_bed_status_0b645b_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['status', 'gender_restriction'], name='beds_bed_status_8e0f61_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['bed_type', 'is_isolation'], name='beds_bed_bed_typ_2fba42_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['status_changed_at'], name='beds_bed_status__3e40c2_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['current_admission'], name='beds_bed_current_448596_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
    ]
