# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=20)),
                ('bed_code', models.CharField(max_length=100, unique=True)),
                ('bed_type', models.CharField(choices=[('icu', 'ICU'), ('general', 'General'), ('isolation', 'Isolation'), ('nicu', 'NICU'), ('emergency', 'Emergency'), ('maternity', 'Maternity'), ('pediatric', 'Pediatric'), ('bariatric', 'Bariatric'), ('burn', 'Burn Unit'), ('psychiatric', 'Psychiatric'), ('recovery', 'Recovery'), ('observation', 'Observation')], default='general', max_length=20)),
                ('is_isolation', models.BooleanField(default=False)),
                ('gender_restriction', models.CharField(choices=[('none', 'None'), ('male_only', 'Male Only'), ('female_only', 'Female Only')], default='none', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('cleaning_required', 'Cleaning Required'), ('cleaning_in_progress', 'Cleaning In Progress'), ('under_maintenance', 'Under Maintenance'), ('blocked', 'Blocked'), ('isolation', 'Isolation')], default='available', max_length=30)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_reason', models.TextField(blank=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.TextField(blank=True)),
                ('under_maintenance_since', models.DateTimeField(blank=True, null=True)),
                ('maintenance_reason', models.TextField(blank=True)),
                ('occupied_since', models.DateTimeField(blank=True, null=True)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('bed_size', models.CharField(choices=[('standard', 'Standard'), ('large', 'Large'), ('bariatric', 'Bariatric'), ('pediatric', 'Pediatric')], default='standard', max_length=20)),
                ('max_patient_weight_kg', models.DecimalField(decimal_places=2, default=150.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ward__department__hospital', 'ward__name', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='BedMaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('issue_description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_type', models.CharField(choices=[('repair', 'Repair'), ('preventive', 'Preventive Maintenance'), ('inspection', 'Inspection'), ('replacement', 'Part Replacement')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentTag',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('life_support', 'Life Support'), ('monitoring', 'Monitoring'), ('mobility', 'Mobility'), ('respiratory', 'Respiratory'), ('infection_control', 'Infection Control'), ('furniture', 'Furniture')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='beds_equipm_categor_58b0f7_idx'), models.Index(fields=['is_active'], name='beds_equipm_is_acti_8c0b5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BedStatusHistory',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('cleaning_required', 'Cleaning Required'), ('cleaning_in_progress', 'Cleaning In Progress'), ('under_maintenance', 'Under Maintenance'), ('blocked', 'Blocked'), ('isolation', 'Isolation')], max_length=30)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.admission')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='beds.bed')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
