# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beds', '0001_initial'),
        ('organizations', '0001_initial'),
        ('admissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedmaintenancerecord',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='beds.bed'),
        ),
        migrations.AddField(
            model_name='bedmaintenancerecord',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedmaintenancerecord',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bed',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_beds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bed',
            name='current_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_bed', to='admissions.admission'),
        ),
        migrations.AddField(
            model_name='bed',
            name='equipment_tags',
            field=models.ManyToManyField(blank=True, related_name='beds', to='beds.equipmenttag'),
        ),
        migrations.AddField(
            model_name='bed',
            name='reserved_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_reserved_bed', to='admissions.admissionrequest'),
        ),
        migrations.AddField(
            model_name='bed',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='organizations.ward'),
        ),
        migrations.AddIndex(
            model_name='bedstatushistory',
            index=models.Index(fields=['bed', '-changed_at'], name='beds_bedsta_bed_id_505ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='bedstatushistory',
            index=models.Index(fields=['status', 'changed_at'], name='beds_bedsta_status_adb57c_idx'),
        ),
        migrations.AddIndex(
            model_name='bedmaintenancerecord',
            index=models.Index(fields=['bed', 'status'], name='beds_bedmai_bed_id_5b8e42_idx'),
        ),
        migrations.AddIndex(
            model_name='bedmaintenancerecord',
            index=models.Index(fields=['severity', 'status'], name='beds_bedmai_severit_70fbb1_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['ward', 'status'], name='beds_bed_ward_id_3352a5_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['ward', 'is_active'], name='beds_bed_ward_id_3444a7_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['status', 'bed_type'], name='beds_bed_status_0b645b_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['status', 'gender_restriction'], name='beds_bed_status_8e0f61_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['bed_type', 'is_isolation'], name='beds_bed_bed_typ_2fba42_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['status_changed_at'], name='beds_bed_status__3e40c2_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['current_admission'], name='beds_bed_current_448596_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
    ]
