# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('dimension_data', models.JSONField(blank=True, default=dict)),
                ('benchmark_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('daily_census', 'Daily Census'), ('bed_utilization', 'Bed Utilization'), ('turnover_time', 'Turnover Time'), ('occupancy_trend', 'Occupancy Trend'), ('departmental_performance', 'Departmental Performance'), ('cleaning_performance', 'Cleaning Performance'), ('admission_discharge', 'Admission/Discharge Summary')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('generation_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('record_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_scheduled_run', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('daily_census', 'Daily Census'), ('bed_utilization', 'Bed Utilization'), ('turnover_time', 'Turnover Time'), ('occupancy_trend', 'Occupancy Trend'), ('departmental_performance', 'Departmental Performance'), ('cleaning_performance', 'Cleaning Performance'), ('admission_discharge', 'Admission/Discharge Summary')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('include_all_departments', models.BooleanField(default=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('schedule_day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('schedule_recipients', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReportEmail',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('report_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='reports.reportrun')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
