# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='report_templates', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_runs', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='reports.reporttemplate'),
        ),
        migrations.AddField(
            model_name='dashboardmetric',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_metrics', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='dashboardmetric',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_metrics', to='organizations.hospital'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['hospital', 'report_type'], name='reports_rep_hospita_5c240d_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_scheduled', 'is_active'], name='reports_rep_is_sche_5174c8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['hospital', 'report_type'], name='reports_rep_hospita_bb34da_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['status'], name='reports_rep_status_f320b8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['created_at'], name='reports_rep_created_cbe32c_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['hospital', 'metric_name'], name='reports_das_hospita_734c90_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['valid_until'], name='reports_das_valid_u_4ccb5d_idx'),
        ),
    ]
