# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='clinicalrequirement',
            name='identified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalrequirement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_requirements', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['mrn'], name='patients_pa_mrn_d0102f_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['ehr_id'], name='patients_pa_ehr_id_6c43cb_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active'], name='patients_pa_is_acti_54ba9f_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['primary_hospital'], name='patients_pa_primary_4a82a8_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalrequirement',
            index=models.Index(fields=['patient', 'is_active'], name='patients_cl_patient_ac9b24_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalrequirement',
            index=models.Index(fields=['requirement_type'], name='patients_cl_require_f7730b_idx'),
        ),
    ]
