# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discharges', '0002_initial'),
        ('beds', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housekeeping', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeepingstaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cleaning_tasks_to_others', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cleaning_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_tasks', to='beds.bed'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cleaning_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='discharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='discharges.discharge'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_cleaning_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='quality_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checked_cleaning', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleaningchecklistitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='housekeeping.cleaningtask'),
        ),
        migrations.AddIndex(
            model_name='housekeepingstaff',
            index=models.Index(fields=['hospital', 'is_active'], name='housekeepin_hospita_c969fc_idx'),
        ),
        migrations.AddIndex(
            model_name='housekeepingstaff',
            index=models.Index(fields=['is_available'], name='housekeepin_is_avai_67cbc0_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['bed', 'status'], name='housekeepin_bed_id_056a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['status', 'priority'], name='housekeepin_status_72e596_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['assigned_to', 'status'], name='housekeepin_assigne_eee6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['sla_deadline'], name='housekeepin_sla_dea_56a2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['sla_breached'], name='housekeepin_sla_bre_5d427b_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['escalated'], name='housekeepin_escalat_03bd6a_idx'),
        ),
    ]
