# Generated by Django 4.2.29 on 2026-04-22 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('admission_source', models.CharField(choices=[('emergency', 'Emergency Department'), ('outpatient', 'Outpatient Clinic'), ('transfer_internal', 'Internal Transfer'), ('transfer_external', 'External Transfer'), ('planned_admission', 'Planned Admission'), ('direct_admission', 'Direct Admission'), ('ehr_integration', 'EHR Integration')], max_length=30)),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('assigned', 'Assigned'), ('admitted', 'Admitted'), ('discharged', 'Discharged'), ('cancelled', 'Cancelled'), ('transferred', 'Transferred')], default='admitted', max_length=20)),
                ('diagnosis_code', models.CharField(blank=True, max_length=20)),
                ('diagnosis_description', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('is_isolation', models.BooleanField(default=False)),
                ('isolation_reason', models.TextField(blank=True)),
                ('isolation_started_at', models.DateTimeField(blank=True, null=True)),
                ('isolation_ended_at', models.DateTimeField(blank=True, null=True)),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('visit_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('external_visit_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('admission_source', models.CharField(choices=[('emergency', 'Emergency Department'), ('outpatient', 'Outpatient Clinic'), ('transfer_internal', 'Internal Transfer'), ('transfer_external', 'External Transfer'), ('planned_admission', 'Planned Admission'), ('direct_admission', 'Direct Admission'), ('ehr_integration', 'EHR Integration')], default='direct_admission', max_length=30)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('requires_isolation', models.BooleanField(default=False)),
                ('requires_icu', models.BooleanField(default=False)),
                ('required_bed_type', models.CharField(choices=[('any', 'Any Available'), ('general', 'General'), ('icu', 'ICU'), ('isolation', 'Isolation'), ('emergency', 'Emergency'), ('maternity', 'Maternity')], default='any', max_length=30)),
                ('clinical_notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('assigned', 'Assigned'), ('admitted', 'Admitted'), ('discharged', 'Discharged'), ('cancelled', 'Cancelled'), ('transferred', 'Transferred')], default='pending', max_length=20)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('queue_position', models.PositiveIntegerField(blank=True, null=True)),
                ('waiting_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('external_request_id', models.CharField(blank=True, max_length=100)),
                ('external_source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'waiting_since'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('transfer_type', models.CharField(choices=[('intra_ward', 'Intra-ward Transfer'), ('inter_ward', 'Inter-ward Transfer'), ('inter_hospital', 'Inter-hospital Transfer')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transport_mode', models.CharField(blank=True, choices=[('walking', 'Walking'), ('wheelchair', 'Wheelchair'), ('stretcher', 'Stretcher'), ('bed', 'Bed'), ('ambulance', 'Ambulance')], max_length=50)),
                ('accompanying_personnel', models.CharField(blank=True, max_length=200)),
                ('special_requirements', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='admissions.admission')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
