# Generated by Django 4.2.29 on 2026-04-22 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beds', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='from_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='beds.bed'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='beds.bed'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_admission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='assigned_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_request_assignments', to='beds.bed'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_admission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requests', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='preferred_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_requests', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='preferred_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_requests', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='reserved_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_requests', to='beds.bed'),
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='admissions.admissionrequest'),
        ),
        migrations.AddField(
            model_name='admission',
            name='admitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='beds.bed'),
        ),
        migrations.AddField(
            model_name='admission',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='admission',
            name='discharged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_discharged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['patient', 'status'], name='admissions__patient_d65035_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['from_hospital', 'status'], name='admissions__from_ho_5298a3_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['to_hospital', 'status'], name='admissions__to_hosp_24d74b_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['admission'], name='admissions__admissi_9b1371_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionrequest',
            index=models.Index(fields=['patient', 'status'], name='admissions__patient_4670dd_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionrequest',
            index=models.Index(fields=['status', 'priority'], name='admissions__status_dbde6f_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionrequest',
            index=models.Index(fields=['preferred_hospital', 'status'], name='admissions__preferr_13dc80_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionrequest',
            index=models.Index(fields=['waiting_since'], name='admissions__waiting_c6a4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionrequest',
            index=models.Index(fields=['external_request_id'], name='admissions__externa_893e65_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['patient', 'status'], name='admissions__patient_89630d_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['bed', 'status'], name='admissions__bed_id_10c950_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['hospital', 'status'], name='admissions__hospita_ca537a_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['admitted_at'], name='admissions__admitte_8829d6_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['visit_number'], name='admissions__visit_n_44ff53_idx'),
        ),
    ]
