# Generated by Django 4.2.29 on 2026-04-22 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('bed_available', 'Bed Available'), ('bed_reserved', 'Bed Reserved'), ('cleaning_sla_breach', 'Cleaning SLA Breach'), ('icu_occupancy_high', 'ICU Occupancy High'), ('admission_queue_deep', 'Admission Queue Deep'), ('discharge_pending', 'Discharge Pending'), ('equipment_alert', 'Equipment Alert'), ('bed_blocked', 'Bed Blocked'), ('system_error', 'System Error')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('notification_count', models.PositiveIntegerField(default=0)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='organizations.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='organizations.hospital')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAlertPreference',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=False)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('notify_push', models.BooleanField(default=False)),
                ('subscribed_alert_types', models.JSONField(default=list)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('min_severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alert_preferences', to='organizations.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'hospital'], name='alerts_user_user_id_fa839c_idx')],
                'unique_together': {('user', 'hospital')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-App Alert'), ('push', 'Push Notification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['alert', 'status'], name='alerts_noti_alert_i_b50b30_idx'), models.Index(fields=['user', 'status'], name='alerts_noti_user_id_1cae1a_idx'), models.Index(fields=['channel', 'status'], name='alerts_noti_channel_4cc13b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('bed_available', 'Bed Available'), ('bed_reserved', 'Bed Reserved'), ('cleaning_sla_breach', 'Cleaning SLA Breach'), ('icu_occupancy_high', 'ICU Occupancy High'), ('admission_queue_deep', 'Admission Queue Deep'), ('discharge_pending', 'Discharge Pending'), ('equipment_alert', 'Equipment Alert'), ('bed_blocked', 'Bed Blocked'), ('system_error', 'System Error')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('threshold_type', models.CharField(choices=[('occupancy_percentage', 'Occupancy Percentage'), ('queue_length', 'Queue Length'), ('time_threshold', 'Time Threshold (minutes)'), ('count', 'Count')], max_length=50)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comparison_operator', models.CharField(choices=[('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('eq', 'Equal')], default='gt', max_length=10)),
                ('applies_to_all_departments', models.BooleanField(default=True)),
                ('notification_channels', models.JSONField(default=list)),
                ('notify_roles', models.JSONField(default=list)),
                ('escalation_enabled', models.BooleanField(default=True)),
                ('escalation_delay_minutes', models.PositiveIntegerField(default=30)),
                ('cooldown_minutes', models.PositiveIntegerField(default=60)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_configs', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='alert_configurations', to='organizations.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_configurations', to='organizations.hospital')),
            ],
            options={
                'ordering': ['alert_type', 'name'],
                'indexes': [models.Index(fields=['hospital', 'alert_type'], name='alerts_aler_hospita_908884_idx'), models.Index(fields=['is_enabled'], name='alerts_aler_is_enab_ddec04_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'is_active'], name='alerts_aler_alert_t_3344e6_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['hospital', 'is_active'], name='alerts_aler_hospita_085e75_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'is_active'], name='alerts_aler_severit_72b37d_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_acknowledged'], name='alerts_aler_is_ackn_88ee24_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['triggered_at'], name='alerts_aler_trigger_5b4eb6_idx'),
        ),
    ]
