# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.db import migrations, models
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('bed_available', 'Bed Available'), ('bed_reserved', 'Bed Reserved'), ('cleaning_sla_breach', 'Cleaning SLA Breach'), ('icu_occupancy_high', 'ICU Occupancy High'), ('admission_queue_deep', 'Admission Queue Deep'), ('discharge_pending', 'Discharge Pending'), ('equipment_alert', 'Equipment Alert'), ('bed_blocked', 'Bed Blocked'), ('system_error', 'System Error')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('notification_count', models.PositiveIntegerField(default=0)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('bed_available', 'Bed Available'), ('bed_reserved', 'Bed Reserved'), ('cleaning_sla_breach', 'Cleaning SLA Breach'), ('icu_occupancy_high', 'ICU Occupancy High'), ('admission_queue_deep', 'Admission Queue Deep'), ('discharge_pending', 'Discharge Pending'), ('equipment_alert', 'Equipment Alert'), ('bed_blocked', 'Bed Blocked'), ('system_error', 'System Error')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('threshold_type', models.CharField(choices=[('occupancy_percentage', 'Occupancy Percentage'), ('queue_length', 'Queue Length'), ('time_threshold', 'Time Threshold (minutes)'), ('count', 'Count')], max_length=50)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comparison_operator', models.CharField(choices=[('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('eq', 'Equal')], default='gt', max_length=10)),
                ('applies_to_all_departments', models.BooleanField(default=True)),
                ('notification_channels', models.JSONField(default=list)),
                ('notify_roles', models.JSONField(default=list)),
                ('escalation_enabled', models.BooleanField(default=True)),
                ('escalation_delay_minutes', models.PositiveIntegerField(default=30)),
                ('cooldown_minutes', models.PositiveIntegerField(default=60)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['alert_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-App Alert'), ('push', 'Push Notification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAlertPreference',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=False)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('notify_push', models.BooleanField(default=False)),
                ('subscribed_alert_types', models.JSONField(default=list)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('min_severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
