# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralertpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='alert_configurations', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_configurations', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='alert',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='alert',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='useralertpreference',
            index=models.Index(fields=['user', 'hospital'], name='alerts_user_user_id_fa839c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useralertpreference',
            unique_together={('user', 'hospital')},
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['alert', 'status'], name='alerts_noti_alert_i_b50b30_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'status'], name='alerts_noti_user_id_1cae1a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['channel', 'status'], name='alerts_noti_channel_4cc13b_idx'),
        ),
        migrations.AddIndex(
            model_name='alertconfiguration',
            index=models.Index(fields=['hospital', 'alert_type'], name='alerts_aler_hospita_908884_idx'),
        ),
        migrations.AddIndex(
            model_name='alertconfiguration',
            index=models.Index(fields=['is_enabled'], name='alerts_aler_is_enab_ddec04_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'is_active'], name='alerts_aler_alert_t_3344e6_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['hospital', 'is_active'], name='alerts_aler_hospita_085e75_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'is_active'], name='alerts_aler_severit_72b37d_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_acknowledged'], name='alerts_aler_is_ackn_88ee24_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['triggered_at'], name='alerts_aler_trigger_5b4eb6_idx'),
        ),
    ]
