# Generated by Django 4.2.29 on 2026-03-26 09:19

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import phonenumber_field.modelfields
import src.lib.utils.uuid7
import src.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.CharField(blank=True, editable=False, max_length=256, null=True, unique=True)),
                ('onboarding_status', models.CharField(choices=[('needs_basic_information', 'Needs Basic Information'), ('needs_email_verification', 'Needs Email Verification'), ('needs_phone_verification', 'Needs Phone Verification'), ('needs_profile_username', 'Needs Profile Username'), ('needs_profile_picture', 'Needs Profile Picture'), ('completed', 'Completed')], db_index=True, default='needs_basic_information', max_length=50)),
                ('profile_picture', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='ProfilePicture')),
                ('picture_url', models.URLField(blank=True, null=True, verbose_name='PictureUrl')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(db_index=True, default=False)),
                ('is_phone_number_verified', models.BooleanField(default=False)),
                ('email_otp_secret', models.CharField(blank=True, default=src.users.models.generate_otp_hash_seed, max_length=128, null=True)),
                ('email_otp_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('email_otp_trials', models.PositiveSmallIntegerField(default=0)),
                ('email_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('email_otp_locked_until', models.DateTimeField(blank=True, null=True)),
                ('phone_otp_secret', models.CharField(blank=True, default=src.users.models.generate_otp_hash_seed, max_length=128, null=True)),
                ('phone_otp_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_otp_trials', models.PositiveSmallIntegerField(default=0)),
                ('phone_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('phone_otp_locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_reset_otp_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('password_reset_otp_trials', models.PositiveSmallIntegerField(default=0)),
                ('password_reset_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_otp_locked_until', models.DateTimeField(blank=True, null=True)),
                ('two_factor_otp_secret', models.CharField(blank=True, default=src.users.models.generate_random_secret, max_length=64, null=True)),
                ('two_factor_otp_trials', models.PositiveSmallIntegerField(default=0)),
                ('two_factor_enabled', models.BooleanField(db_index=True, default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            bases=(src.users.models.OnboardingMixin, src.users.models.UserAuthMixin, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='recoverycode',
            constraint=models.UniqueConstraint(fields=('user', 'code_hash'), name='unique_recovery_code_per_user'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'),
        ),
    ]
