# Generated by Django 4.2.29 on 2026-04-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_onboarding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='onboarding_status',
            field=models.CharField(choices=[('needs_basic_information', 'Needs Basic Information'), ('needs_password', 'Needs Password'), ('needs_email_verification', 'Needs Email Verification'), ('needs_phone_verification', 'Needs Phone Verification'), ('needs_profile_username', 'Needs Profile Username'), ('needs_profile_picture', 'Needs Profile Picture'), ('needs_hospital', 'Needs Hospital Affiliation'), ('completed', 'Completed')], db_index=True, default='needs_basic_information', max_length=50),
        ),
    ]
