# Generated by Django 4.2.29 on 2026-03-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mfa_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mfachallenge',
            new_name='users_mfach_session_3332c9_idx',
            old_name='users_mfach_session_5f3549_idx',
        ),
        migrations.RenameIndex(
            model_name='mfachallenge',
            new_name='users_mfach_expires_8d9cf4_idx',
            old_name='users_mfach_expires_e3f98f_idx',
        ),
        migrations.RenameIndex(
            model_name='mfamethod',
            new_name='users_mfame_user_id_6f2007_idx',
            old_name='users_mfame_user_id_911b09_idx',
        ),
        migrations.RenameIndex(
            model_name='mfasession',
            new_name='users_mfase_user_id_5ed37d_idx',
            old_name='users_mfase_user_id_3857cc_idx',
        ),
        migrations.RenameIndex(
            model_name='mfasession',
            new_name='users_mfase_verifie_203270_idx',
            old_name='users_mfase_verifie_e5cdd8_idx',
        ),
        migrations.RenameIndex(
            model_name='mfatrusteddevice',
            new_name='users_mfatr_user_id_832e6f_idx',
            old_name='users_mfatr_user_id_51972c_idx',
        ),
    ]
