# Generated by Django 4.2.29 on 2026-04-24 11:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('floors', models.PositiveIntegerField(default=1)),
                ('has_elevator', models.BooleanField(default=True)),
                ('is_accessible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('department_type', models.CharField(choices=[('general_medicine', 'General Medicine'), ('surgery', 'Surgery'), ('icu', 'ICU'), ('emergency', 'Emergency'), ('maternity', 'Maternity'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('oncology', 'Oncology'), ('orthopedics', 'Orthopedics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('geriatrics', 'Geriatrics'), ('rehabilitation', 'Rehabilitation')], max_length=50)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('wing', models.CharField(blank=True, max_length=50)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('gender_restriction', models.CharField(choices=[('none', 'None'), ('male_only', 'Male Only'), ('female_only', 'Female Only')], default='none', max_length=20)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('nurse_station_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('hospital_type', models.CharField(choices=[('general', 'General Hospital'), ('specialty', 'Specialty Hospital'), ('teaching', 'Teaching Hospital'), ('children', "Children's Hospital"), ('psychiatric', 'Psychiatric Hospital'), ('rehabilitation', 'Rehabilitation Hospital')], default='general', max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('icu_beds', models.PositiveIntegerField(default=0)),
                ('emergency_beds', models.PositiveIntegerField(default=0)),
                ('cleaning_sla_minutes', models.PositiveIntegerField(default=60)),
                ('auto_assign_cleaning', models.BooleanField(default=True)),
                ('require_discharge_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system_administrator', 'System Administrator'), ('bed_manager', 'Bed Manager'), ('nurse_supervisor', 'Nurse Supervisor'), ('admission_staff', 'Admission Staff'), ('housekeeping_staff', 'Housekeeping Staff'), ('executive_viewer', 'Executive / Viewer'), ('clinical_staff', 'Clinical Staff'), ('ward_clerk', 'Ward Clerk')], max_length=50)),
                ('additional_permissions', models.JSONField(blank=True, default=dict)),
                ('restricted_permissions', models.JSONField(blank=True, default=list)),
                ('employee_id', models.CharField(blank=True, max_length=100)),
                ('is_primary_assignment', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hospital Staff',
                'ordering': ['-is_primary_assignment', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Code must contain only uppercase letters, numbers, and underscores', regex='^[A-Z0-9_]+$')])),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('allow_cross_hospital_transfers', models.BooleanField(default=True)),
                ('allow_centralized_reporting', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ward_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('multi', 'Multi-bed Room'), ('bay', 'Bay'), ('icu', 'ICU Pod'), ('emergency', 'Emergency Bay')], max_length=50)),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('has_bathroom', models.BooleanField(default=True)),
                ('has_oxygen', models.BooleanField(default=False)),
                ('has_suction', models.BooleanField(default=False)),
                ('has_monitor', models.BooleanField(default=False)),
                ('has_ventilator', models.BooleanField(default=False)),
                ('is_isolation_capable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='organizations.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
