# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalstaff',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalstaff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_staff', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='hospitalstaff',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='hospitalstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_staff_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hospitals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='organizations.building'),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='building',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='organizations.hospital'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['department', 'is_active'], name='organizatio_departm_fd199b_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['ward_type'], name='organizatio_ward_ty_ac5d67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together={('department', 'code')},
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['code'], name='organizatio_code_9d1386_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_1ffc28_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_at'], name='organizatio_created_dfd536_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalstaff',
            index=models.Index(fields=['hospital', 'role'], name='organizatio_hospita_eac8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalstaff',
            index=models.Index(fields=['user', 'is_active'], name='organizatio_user_id_47017a_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalstaff',
            index=models.Index(fields=['role', 'is_active'], name='organizatio_role_792659_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hospitalstaff',
            unique_together={('user', 'hospital', 'department', 'role')},
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_37608c_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['code'], name='organizatio_code_31f9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['created_at'], name='organizatio_created_92abb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hospital',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['hospital', 'is_active'], name='organizatio_hospita_1c627a_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['department_type'], name='organizatio_departm_7025f2_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['gender_restriction'], name='organizatio_gender__cb602c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hospital', 'code')},
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['hospital', 'is_active'], name='organizatio_hospita_da8149_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('hospital', 'code')},
        ),
    ]
