# Generated by Django 4.2.29 on 2026-04-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_alter_hospital_address_alter_hospital_city_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalStaffInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=src.lib.utils.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("system_administrator", "System Administrator"),
                            ("bed_manager", "Bed Manager"),
                            ("nurse_supervisor", "Nurse Supervisor"),
                            ("admission_staff", "Admission Staff"),
                            ("housekeeping_staff", "Housekeeping Staff"),
                            ("executive_viewer", "Executive / Viewer"),
                            ("clinical_staff", "Clinical Staff"),
                            ("ward_clerk", "Ward Clerk"),
                        ],
                        max_length=50,
                    ),
                ),
                ("employee_id", models.CharField(blank=True, max_length=100)),
                ("message", models.CharField(blank=True, max_length=255)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_hospital_staff_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_invitations",
                        to="organizations.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_invitations",
                        to="organizations.hospital",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_hospital_staff_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="hospitalstaffinvitation",
            index=models.Index(
                fields=["hospital", "status"],
                name="organizatio_hospita_0c53b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hospitalstaffinvitation",
            index=models.Index(
                fields=["email", "status"],
                name="organizatio_email_41cc9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hospitalstaffinvitation",
            index=models.Index(
                fields=["expires_at"],
                name="organizatio_expires_3e3911_idx",
            ),
        ),
    ]
