# Generated by Django 4.2.29 on 2026-04-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_hospitalstaffinvitation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hospitalstaffinvitation',
            new_name='organizatio_hospita_3486e9_idx',
            old_name='organizatio_hospita_0c53b2_idx',
        ),
        migrations.RenameIndex(
            model_name='hospitalstaffinvitation',
            new_name='organizatio_email_4e1a93_idx',
            old_name='organizatio_email_41cc9b_idx',
        ),
        migrations.RenameIndex(
            model_name='hospitalstaffinvitation',
            new_name='organizatio_expires_5d35b1_idx',
            old_name='organizatio_expires_3e3911_idx',
        ),
    ]
