# Generated by Django 4.2.29 on 2026-04-22 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEndpoint',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('integration_type', models.CharField(choices=[('fhir', 'FHIR API'), ('hl7', 'HL7 v2'), ('adt', 'ADT Feed'), ('webhook', 'Webhook'), ('sms_gateway', 'SMS Gateway'), ('email_gateway', 'Email Gateway'), ('identity_provider', 'Identity Provider'), ('analytics', 'Analytics Platform')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('configuration_pending', 'Configuration Pending')], default='configuration_pending', max_length=30)),
                ('base_url', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('auth_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=500)),
                ('webhook_url', models.URLField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('supports_adt', models.BooleanField(default=True)),
                ('supports_patient_query', models.BooleanField(default=False)),
                ('supports_bed_status', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_result', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integrations', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_endpoints', to='organizations.hospital')),
            ],
            options={
                'ordering': ['hospital', 'integration_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FHIRResourceCache',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=100)),
                ('fhir_data', models.JSONField()),
                ('cached_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhir_cache', to='integrations.integrationendpoint')),
            ],
            options={
                'ordering': ['-cached_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('secret', models.CharField(blank=True, max_length=500)),
                ('events', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_delivery_status', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='organizations.hospital')),
            ],
            options={
                'ordering': ['hospital', 'name'],
                'indexes': [models.Index(fields=['hospital', 'is_active'], name='integration_hospita_e1c814_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationMessage',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('message_type', models.CharField(choices=[('adt_a01', 'ADT^A01 - Admit'), ('adt_a02', 'ADT^A02 - Transfer'), ('adt_a03', 'ADT^A03 - Discharge'), ('adt_a08', 'ADT^A08 - Update'), ('adt_a11', 'ADT^A11 - Cancel Admit'), ('fhir_patient', 'FHIR Patient'), ('fhir_encounter', 'FHIR Encounter'), ('fhir_location', 'FHIR Location'), ('webhook', 'Webhook'), ('api_call', 'API Call')], max_length=50)),
                ('raw_payload', models.TextField()),
                ('parsed_payload', models.JSONField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('ignored', 'Ignored')], default='received', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('patient_mrn', models.CharField(blank=True, db_index=True, max_length=50)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='integrations.integrationendpoint')),
                ('related_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_messages', to='admissions.admission')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['endpoint', 'status'], name='integration_endpoin_f9c826_idx'), models.Index(fields=['message_type', 'status'], name='integration_message_2ef6b6_idx'), models.Index(fields=['patient_mrn'], name='integration_patient_fd692f_idx'), models.Index(fields=['correlation_id'], name='integration_correla_ec7dea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='integrationendpoint',
            index=models.Index(fields=['hospital', 'integration_type'], name='integration_hospita_816225_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationendpoint',
            index=models.Index(fields=['status'], name='integration_status_f05953_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationendpoint',
            index=models.Index(fields=['is_active'], name='integration_is_acti_34957f_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirresourcecache',
            index=models.Index(fields=['resource_type', 'resource_id'], name='integration_resourc_1b4989_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirresourcecache',
            index=models.Index(fields=['expires_at'], name='integration_expires_eab5a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fhirresourcecache',
            unique_together={('endpoint', 'resource_type', 'resource_id')},
        ),
    ]
