# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.db import migrations, models
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRResourceCache',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=100)),
                ('fhir_data', models.JSONField()),
                ('cached_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-cached_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEndpoint',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('integration_type', models.CharField(choices=[('fhir', 'FHIR API'), ('hl7', 'HL7 v2'), ('adt', 'ADT Feed'), ('webhook', 'Webhook'), ('sms_gateway', 'SMS Gateway'), ('email_gateway', 'Email Gateway'), ('identity_provider', 'Identity Provider'), ('analytics', 'Analytics Platform')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('configuration_pending', 'Configuration Pending')], default='configuration_pending', max_length=30)),
                ('base_url', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('auth_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=500)),
                ('webhook_url', models.URLField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('supports_adt', models.BooleanField(default=True)),
                ('supports_patient_query', models.BooleanField(default=False)),
                ('supports_bed_status', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_result', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hospital', 'integration_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationMessage',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('message_type', models.CharField(choices=[('adt_a01', 'ADT^A01 - Admit'), ('adt_a02', 'ADT^A02 - Transfer'), ('adt_a03', 'ADT^A03 - Discharge'), ('adt_a08', 'ADT^A08 - Update'), ('adt_a11', 'ADT^A11 - Cancel Admit'), ('fhir_patient', 'FHIR Patient'), ('fhir_encounter', 'FHIR Encounter'), ('fhir_location', 'FHIR Location'), ('webhook', 'Webhook'), ('api_call', 'API Call')], max_length=50)),
                ('raw_payload', models.TextField()),
                ('parsed_payload', models.JSONField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('ignored', 'Ignored')], default='received', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('patient_mrn', models.CharField(blank=True, db_index=True, max_length=50)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('secret', models.CharField(blank=True, max_length=500)),
                ('events', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_delivery_status', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hospital', 'name'],
            },
        ),
    ]
