# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('organizations', '0001_initial'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksubscription',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='integrationmessage',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='integrations.integrationendpoint'),
        ),
        migrations.AddField(
            model_name='integrationmessage',
            name='related_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_messages', to='admissions.admission'),
        ),
    ]
