# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationendpoint',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integrationendpoint',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_endpoints', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='fhirresourcecache',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhir_cache', to='integrations.integrationendpoint'),
        ),
        migrations.AddIndex(
            model_name='webhooksubscription',
            index=models.Index(fields=['hospital', 'is_active'], name='integration_hospita_e1c814_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationmessage',
            index=models.Index(fields=['endpoint', 'status'], name='integration_endpoin_f9c826_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationmessage',
            index=models.Index(fields=['message_type', 'status'], name='integration_message_2ef6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationmessage',
            index=models.Index(fields=['patient_mrn'], name='integration_patient_fd692f_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationmessage',
            index=models.Index(fields=['correlation_id'], name='integration_correla_ec7dea_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationendpoint',
            index=models.Index(fields=['hospital', 'integration_type'], name='integration_hospita_816225_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationendpoint',
            index=models.Index(fields=['status'], name='integration_status_f05953_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationendpoint',
            index=models.Index(fields=['is_active'], name='integration_is_acti_34957f_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirresourcecache',
            index=models.Index(fields=['resource_type', 'resource_id'], name='integration_resourc_1b4989_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirresourcecache',
            index=models.Index(fields=['expires_at'], name='integration_expires_eab5a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fhirresourcecache',
            unique_together={('endpoint', 'resource_type', 'resource_id')},
        ),
    ]
