# Generated by Django 4.2.29 on 2026-04-22 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beds', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargePlanning',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('expected_discharge_date', models.DateField()),
                ('expected_discharge_time', models.TimeField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI-generated confidence score for prediction', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('ready', 'Ready for Discharge'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('barriers', models.JSONField(blank=True, default=list)),
                ('barrier_notes', models.TextField(blank=True)),
                ('disposition_plan', models.TextField(blank=True)),
                ('home_care_required', models.BooleanField(default=False)),
                ('equipment_needs', models.JSONField(blank=True, default=list)),
                ('transport_arranged', models.BooleanField(default=False)),
                ('transport_details', models.CharField(blank=True, max_length=200)),
                ('medications_reconciled', models.BooleanField(default=False)),
                ('prescriptions_ready', models.BooleanField(default=False)),
                ('physician_approved', models.BooleanField(default=False)),
                ('physician_approved_at', models.DateTimeField(blank=True, null=True)),
                ('nurse_approved', models.BooleanField(default=False)),
                ('nurse_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_plans', to='admissions.admission')),
                ('case_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_discharge_plans', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_plans', to='patients.patient')),
                ('planned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discharge_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expected_discharge_date'],
                'indexes': [models.Index(fields=['admission', 'status'], name='discharges__admissi_260086_idx'), models.Index(fields=['expected_discharge_date'], name='discharges__expecte_ae219d_idx'), models.Index(fields=['status'], name='discharges__status_bad8a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('approval_required', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_type', models.CharField(choices=[('routine', 'Routine'), ('ama', 'Against Medical Advice'), ('transfer', 'Transfer'), ('deceased', 'Deceased'), ('absconded', 'Absconded'), ('left_ama', 'Left Against Medical Advice')], default='routine', max_length=50)),
                ('destination', models.CharField(choices=[('home', 'Home'), ('other_hospital', 'Other Hospital'), ('rehabilitation', 'Rehabilitation Facility'), ('nursing_home', 'Nursing Home'), ('hospice', 'Hospice'), ('deceased', 'Deceased')], default='home', max_length=30)),
                ('destination_details', models.TextField(blank=True)),
                ('discharge_diagnosis', models.TextField(blank=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('follow_up_appointment', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_process_started_at', models.DateTimeField(blank=True, null=True)),
                ('patient_left_at', models.DateTimeField(blank=True, null=True)),
                ('bed_available_at', models.DateTimeField(blank=True, null=True)),
                ('turnover_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('external_discharge_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='admissions.admission')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discharges', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to='beds.bed')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_discharges', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharges', to='organizations.hospital')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_discharges', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharges', to='patients.patient')),
            ],
            options={
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='discharges__patient_e7fdf0_idx'), models.Index(fields=['hospital', 'status'], name='discharges__hospita_d9134d_idx'), models.Index(fields=['bed', 'status'], name='discharges__bed_id_d016e1_idx'), models.Index(fields=['status', 'initiated_at'], name='discharges__status_7f4b71_idx')],
            },
        ),
    ]
