# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('approval_required', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_type', models.CharField(choices=[('routine', 'Routine'), ('ama', 'Against Medical Advice'), ('transfer', 'Transfer'), ('deceased', 'Deceased'), ('absconded', 'Absconded'), ('left_ama', 'Left Against Medical Advice')], default='routine', max_length=50)),
                ('destination', models.CharField(choices=[('home', 'Home'), ('other_hospital', 'Other Hospital'), ('rehabilitation', 'Rehabilitation Facility'), ('nursing_home', 'Nursing Home'), ('hospice', 'Hospice'), ('deceased', 'Deceased')], default='home', max_length=30)),
                ('destination_details', models.TextField(blank=True)),
                ('discharge_diagnosis', models.TextField(blank=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('follow_up_appointment', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_process_started_at', models.DateTimeField(blank=True, null=True)),
                ('patient_left_at', models.DateTimeField(blank=True, null=True)),
                ('bed_available_at', models.DateTimeField(blank=True, null=True)),
                ('turnover_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('external_discharge_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='DischargePlanning',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('expected_discharge_date', models.DateField()),
                ('expected_discharge_time', models.TimeField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI-generated confidence score for prediction', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('ready', 'Ready for Discharge'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('barriers', models.JSONField(blank=True, default=list)),
                ('barrier_notes', models.TextField(blank=True)),
                ('disposition_plan', models.TextField(blank=True)),
                ('home_care_required', models.BooleanField(default=False)),
                ('equipment_needs', models.JSONField(blank=True, default=list)),
                ('transport_arranged', models.BooleanField(default=False)),
                ('transport_details', models.CharField(blank=True, max_length=200)),
                ('medications_reconciled', models.BooleanField(default=False)),
                ('prescriptions_ready', models.BooleanField(default=False)),
                ('physician_approved', models.BooleanField(default=False)),
                ('physician_approved_at', models.DateTimeField(blank=True, null=True)),
                ('nurse_approved', models.BooleanField(default=False)),
                ('nurse_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_plans', to='admissions.admission')),
            ],
            options={
                'ordering': ['expected_discharge_date'],
            },
        ),
    ]
