# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beds', '0002_initial'),
        ('discharges', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('admissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargeplanning',
            name='case_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_discharge_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dischargeplanning',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_plans', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='dischargeplanning',
            name='planned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discharge_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discharge',
            name='admission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='admissions.admission'),
        ),
        migrations.AddField(
            model_name='discharge',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discharges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discharge',
            name='bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to='beds.bed'),
        ),
        migrations.AddField(
            model_name='discharge',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_discharges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discharge',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharges', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='discharge',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_discharges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discharge',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharges', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='dischargeplanning',
            index=models.Index(fields=['admission', 'status'], name='discharges__admissi_260086_idx'),
        ),
        migrations.AddIndex(
            model_name='dischargeplanning',
            index=models.Index(fields=['expected_discharge_date'], name='discharges__expecte_ae219d_idx'),
        ),
        migrations.AddIndex(
            model_name='dischargeplanning',
            index=models.Index(fields=['status'], name='discharges__status_bad8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='discharge',
            index=models.Index(fields=['patient', 'status'], name='discharges__patient_e7fdf0_idx'),
        ),
        migrations.AddIndex(
            model_name='discharge',
            index=models.Index(fields=['hospital', 'status'], name='discharges__hospita_d9134d_idx'),
        ),
        migrations.AddIndex(
            model_name='discharge',
            index=models.Index(fields=['bed', 'status'], name='discharges__bed_id_d016e1_idx'),
        ),
        migrations.AddIndex(
            model_name='discharge',
            index=models.Index(fields=['status', 'initiated_at'], name='discharges__status_7f4b71_idx'),
        ),
    ]
