# Generated by Django 4.2.29 on 2026-04-22 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('current_view', models.CharField(blank=True, max_length=100)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('current_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_presence', to='organizations.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'is_online'], name='realtime_us_user_id_a4485b_idx'), models.Index(fields=['hospital', 'is_online'], name='realtime_us_hospita_2ad632_idx'), models.Index(fields=['last_seen_at'], name='realtime_us_last_se_3dcde1_idx')],
            },
        ),
        migrations.CreateModel(
            name='RealtimeEvent',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('channel', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('target_users', models.JSONField(blank=True, default=list)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_events', to='organizations.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'event_type'], name='realtime_re_hospita_07a2a7_idx'), models.Index(fields=['channel'], name='realtime_re_channel_8a32cc_idx'), models.Index(fields=['expires_at'], name='realtime_re_expires_5beee9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardSubscription',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('dashboard_type', models.CharField(choices=[('operational', 'Operational Dashboard'), ('department', 'Department View'), ('executive', 'Executive Dashboard'), ('housekeeping', 'Housekeeping Dashboard'), ('admission', 'Admission Dashboard')], max_length=50)),
                ('channel_name', models.CharField(max_length=200)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_subscribers', to='organizations.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['hospital', 'dashboard_type'], name='realtime_da_hospita_6b6fdd_idx'), models.Index(fields=['channel_name'], name='realtime_da_channel_fd7939_idx')],
            },
        ),
    ]
