# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSubscription',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('dashboard_type', models.CharField(choices=[('operational', 'Operational Dashboard'), ('department', 'Department View'), ('executive', 'Executive Dashboard'), ('housekeeping', 'Housekeeping Dashboard'), ('admission', 'Admission Dashboard')], max_length=50)),
                ('channel_name', models.CharField(max_length=200)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='RealtimeEvent',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('channel', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('target_users', models.JSONField(blank=True, default=list)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('current_view', models.CharField(blank=True, max_length=100)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('current_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_presence', to='organizations.hospital')),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
