# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpresence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realtimeevent',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_events', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='dashboardsubscription',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.department'),
        ),
        migrations.AddField(
            model_name='dashboardsubscription',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_subscribers', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='dashboardsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userpresence',
            index=models.Index(fields=['user', 'is_online'], name='realtime_us_user_id_a4485b_idx'),
        ),
        migrations.AddIndex(
            model_name='userpresence',
            index=models.Index(fields=['hospital', 'is_online'], name='realtime_us_hospita_2ad632_idx'),
        ),
        migrations.AddIndex(
            model_name='userpresence',
            index=models.Index(fields=['last_seen_at'], name='realtime_us_last_se_3dcde1_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeevent',
            index=models.Index(fields=['hospital', 'event_type'], name='realtime_re_hospita_07a2a7_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeevent',
            index=models.Index(fields=['channel'], name='realtime_re_channel_8a32cc_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeevent',
            index=models.Index(fields=['expires_at'], name='realtime_re_expires_5beee9_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardsubscription',
            index=models.Index(fields=['hospital', 'dashboard_type'], name='realtime_da_hospita_6b6fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardsubscription',
            index=models.Index(fields=['channel_name'], name='realtime_da_channel_fd7939_idx'),
        ),
    ]
