# Generated by Django 4.2.29 on 2026-04-22 23:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housekeeping', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionQueueSnapshot',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('snapshot_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_pending', models.PositiveIntegerField()),
                ('urgent_pending', models.PositiveIntegerField(default=0)),
                ('emergency_pending', models.PositiveIntegerField(default=0)),
                ('average_wait_minutes', models.PositiveIntegerField()),
                ('max_wait_minutes', models.PositiveIntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_snapshots', to='organizations.hospital')),
            ],
            options={
                'ordering': ['-snapshot_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesMetric',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('granularity', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='hour', max_length=20)),
                ('dimension_1', models.CharField(blank=True, max_length=100)),
                ('dimension_2', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_series_metrics', to='organizations.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series_metrics', to='organizations.hospital')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['hospital', 'metric_name', 'timestamp'], name='dashboard_t_hospita_f71a4e_idx'), models.Index(fields=['hospital', 'department', 'metric_name'], name='dashboard_t_hospita_5ad4bf_idx'), models.Index(fields=['granularity', 'timestamp'], name='dashboard_t_granula_543661_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyCensus',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('census_date', models.DateField(db_index=True)),
                ('midnight_census', models.PositiveIntegerField()),
                ('admissions', models.PositiveIntegerField()),
                ('discharges', models.PositiveIntegerField()),
                ('transfers_in', models.PositiveIntegerField()),
                ('transfers_out', models.PositiveIntegerField()),
                ('available_beds', models.PositiveIntegerField()),
                ('total_beds', models.PositiveIntegerField()),
                ('occupancy_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_los', models.DecimalField(decimal_places=2, max_digits=5)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_census', to='organizations.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_census', to='organizations.hospital')),
            ],
            options={
                'ordering': ['-census_date'],
                'indexes': [models.Index(fields=['hospital', 'census_date'], name='dashboard_d_hospita_385609_idx')],
                'unique_together': {('hospital', 'department', 'census_date')},
            },
        ),
        migrations.CreateModel(
            name='CleaningPerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('tasks_completed', models.PositiveIntegerField()),
                ('tasks_overdue', models.PositiveIntegerField()),
                ('tasks_escalated', models.PositiveIntegerField()),
                ('average_turnaround_minutes', models.PositiveIntegerField()),
                ('sla_compliance_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_metrics', to='organizations.hospital')),
                ('housekeeping_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='housekeeping.housekeepingstaff')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('housekeeping_staff', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BedAvailabilitySnapshot',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('snapshot_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_beds', models.PositiveIntegerField()),
                ('available_beds', models.PositiveIntegerField()),
                ('occupied_beds', models.PositiveIntegerField()),
                ('reserved_beds', models.PositiveIntegerField()),
                ('cleaning_required_beds', models.PositiveIntegerField()),
                ('cleaning_in_progress_beds', models.PositiveIntegerField()),
                ('maintenance_beds', models.PositiveIntegerField()),
                ('blocked_beds', models.PositiveIntegerField()),
                ('isolation_beds', models.PositiveIntegerField()),
                ('total_icu_beds', models.PositiveIntegerField(default=0)),
                ('occupied_icu_beds', models.PositiveIntegerField(default=0)),
                ('available_icu_beds', models.PositiveIntegerField(default=0)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('icu_occupancy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_snapshots', to='organizations.hospital')),
            ],
            options={
                'ordering': ['-snapshot_time'],
                'indexes': [models.Index(fields=['hospital', 'snapshot_time'], name='dashboard_b_hospita_ba01b0_idx')],
            },
        ),
    ]
