# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.db import migrations, models
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionQueueSnapshot',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('snapshot_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_pending', models.PositiveIntegerField()),
                ('urgent_pending', models.PositiveIntegerField(default=0)),
                ('emergency_pending', models.PositiveIntegerField(default=0)),
                ('average_wait_minutes', models.PositiveIntegerField()),
                ('max_wait_minutes', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-snapshot_time'],
            },
        ),
        migrations.CreateModel(
            name='BedAvailabilitySnapshot',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('snapshot_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_beds', models.PositiveIntegerField()),
                ('available_beds', models.PositiveIntegerField()),
                ('occupied_beds', models.PositiveIntegerField()),
                ('reserved_beds', models.PositiveIntegerField()),
                ('cleaning_required_beds', models.PositiveIntegerField()),
                ('cleaning_in_progress_beds', models.PositiveIntegerField()),
                ('maintenance_beds', models.PositiveIntegerField()),
                ('blocked_beds', models.PositiveIntegerField()),
                ('isolation_beds', models.PositiveIntegerField()),
                ('total_icu_beds', models.PositiveIntegerField(default=0)),
                ('occupied_icu_beds', models.PositiveIntegerField(default=0)),
                ('available_icu_beds', models.PositiveIntegerField(default=0)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('icu_occupancy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['-snapshot_time'],
            },
        ),
        migrations.CreateModel(
            name='CleaningPerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('tasks_completed', models.PositiveIntegerField()),
                ('tasks_overdue', models.PositiveIntegerField()),
                ('tasks_escalated', models.PositiveIntegerField()),
                ('average_turnaround_minutes', models.PositiveIntegerField()),
                ('sla_compliance_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyCensus',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('census_date', models.DateField(db_index=True)),
                ('midnight_census', models.PositiveIntegerField()),
                ('admissions', models.PositiveIntegerField()),
                ('discharges', models.PositiveIntegerField()),
                ('transfers_in', models.PositiveIntegerField()),
                ('transfers_out', models.PositiveIntegerField()),
                ('available_beds', models.PositiveIntegerField()),
                ('total_beds', models.PositiveIntegerField()),
                ('occupancy_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_los', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['-census_date'],
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesMetric',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('granularity', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='hour', max_length=20)),
                ('dimension_1', models.CharField(blank=True, max_length=100)),
                ('dimension_2', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
