# Generated by Django 4.2.29 on 2026-04-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housekeeping', '0001_initial'),
        ('organizations', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriesmetric',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_series_metrics', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='timeseriesmetric',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series_metrics', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='dailycensus',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_census', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='dailycensus',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_census', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='cleaningperformancemetric',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_metrics', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='cleaningperformancemetric',
            name='housekeeping_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='housekeeping.housekeepingstaff'),
        ),
        migrations.AddField(
            model_name='bedavailabilitysnapshot',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_snapshots', to='organizations.hospital'),
        ),
        migrations.AddField(
            model_name='admissionqueuesnapshot',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_snapshots', to='organizations.hospital'),
        ),
        migrations.AddIndex(
            model_name='timeseriesmetric',
            index=models.Index(fields=['hospital', 'metric_name', 'timestamp'], name='dashboard_t_hospita_f71a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='timeseriesmetric',
            index=models.Index(fields=['hospital', 'department', 'metric_name'], name='dashboard_t_hospita_5ad4bf_idx'),
        ),
        migrations.AddIndex(
            model_name='timeseriesmetric',
            index=models.Index(fields=['granularity', 'timestamp'], name='dashboard_t_granula_543661_idx'),
        ),
        migrations.AddIndex(
            model_name='dailycensus',
            index=models.Index(fields=['hospital', 'census_date'], name='dashboard_d_hospita_385609_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailycensus',
            unique_together={('hospital', 'department', 'census_date')},
        ),
        migrations.AlterUniqueTogether(
            name='cleaningperformancemetric',
            unique_together={('housekeeping_staff', 'date')},
        ),
        migrations.AddIndex(
            model_name='bedavailabilitysnapshot',
            index=models.Index(fields=['hospital', 'snapshot_time'], name='dashboard_b_hospita_ba01b0_idx'),
        ),
    ]
